name: serbizio_ph
description: Serbizio Instant Services connects you with trusted service providers and companies for all your needs, from household help to restaurant services, construction, and BPO.
version: 1.0.0+1

environment:
  # sdk: '>=3.0.6 <4.0.0'
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.5
  gap: ^3.0.1
  colorful_safe_area: ^1.0.0
  get: ^4.6.5
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  introduction_screen: ^3.1.12
  connectivity_plus: ^5.0.2
  icons_plus: ^5.0.0
  intl: ^0.19.0
  cloud_firestore: ^4.14.0
  get_storage: ^2.1.1
  google_sign_in: ^6.1.6
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  firebase_database: ^10.3.8
  package_info_plus: ^4.2.0
  url_launcher: ^6.1.14
  sliding_up_panel: ^2.0.0+1
  share_plus: ^7.2.1
  firebase_messaging: ^14.7.10
  app_settings: ^5.1.1
  carousel_slider: ^4.2.1

  realm: #^1.5.0
  provider: ^6.0.5
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  like_button: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_native_splash:
  color: "#7045F2"
  dark_color: "#7045F2"
  image: assets/images/ic_launcher_2.png
  dark_image: assets/images/ic_launcher_2.png
  android_12:
    color: "#7045F2"
    dark_color: "#7045F2"
    image: assets/images/ic_launcher_1.png
    dark_image: assets/images/ic_launcher_1.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#FFFFFF"
  web: false
  ios: false

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/config/

  fonts:
    - family: Epilogue
      fonts:
        - asset: fonts/Epilogue-Regular.ttf
          weight: 400
        - asset: fonts/Epilogue-Medium.ttf
          weight: 500
        - asset: fonts/Epilogue-SemiBold.ttf
          weight: 600
        - asset: fonts/Epilogue-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700